# Generated by the protocol buffer compiler.  DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

class HandwritingInferenceStub(object):
    """The greeting service definition."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recognize = channel.unary_unary(
                '/handwriting_inference.HandwritingInference/Recognize',
                request_serializer=None,
                response_deserializer=None,
                )
        self.BatchRecognize = channel.unary_unary(
                '/handwriting_inference.HandwritingInference/BatchRecognize',
                request_serializer=None,
                response_deserializer=None,
                )
        self.TrainModel = channel.unary_unary(
                '/handwriting_inference.HandwritingInference/TrainModel',
                request_serializer=None,
                response_deserializer=None,
                )
        self.GetTrainingStatus = channel.unary_unary(
                '/handwriting_inference.HandwritingInference/GetTrainingStatus',
                request_serializer=None,
                response_deserializer=None,
                )
        self.UpdateConfig = channel.unary_unary(
                '/handwriting_inference.HandwritingInference/UpdateConfig',
                request_serializer=None,
                response_deserializer=None,
                )


class HandwritingInferenceServicer(object):
    """The greeting service definition."""

    def Recognize(self, request, context):
        """识别单张图片"""
        raise NotImplementedError('Method not implemented!')

    def BatchRecognize(self, request, context):
        """批量识别"""
        raise NotImplementedError('Method not implemented!')

    def TrainModel(self, request, context):
        """触发训练"""
        raise NotImplementedError('Method not implemented!')

    def GetTrainingStatus(self, request, context):
        """获取训练状态"""
        raise NotImplementedError('Method not implemented!')

    def UpdateConfig(self, request, context):
        """更新配置"""
        raise NotImplementedError('Method not implemented!')


def add_HandwritingInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=None,
                    response_serializer=None,
            ),
            'BatchRecognize': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchRecognize,
                    request_deserializer=None,
                    response_serializer=None,
            ),
            'TrainModel': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainModel,
                    request_deserializer=None,
                    response_serializer=None,
            ),
            'GetTrainingStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingStatus,
                    request_deserializer=None,
                    response_serializer=None,
            ),
            'UpdateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfig,
                    request_deserializer=None,
                    response_serializer=None,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'handwriting_inference.HandwritingInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


def add_HandwritingInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=None,
                    response_serializer=None,
            ),
            'BatchRecognize': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchRecognize,
                    request_deserializer=None,
                    response_serializer=None,
            ),
            'TrainModel': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainModel,
                    request_deserializer=None,
                    response_serializer=None,
            ),
            'GetTrainingStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingStatus,
                    request_deserializer=None,
                    response_serializer=None,
            ),
            'UpdateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfig,
                    request_deserializer=None,
                    response_serializer=None,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'handwriting_inference.HandwritingInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
