# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import handwriting_inference_pb2 as handwriting__inference__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in handwriting_inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HandwritingInferenceStub(object):
    """字迹识别服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recognize = channel.unary_unary(
                '/handwriting_inference.HandwritingInference/Recognize',
                request_serializer=handwriting__inference__pb2.RecognizeRequest.SerializeToString,
                response_deserializer=handwriting__inference__pb2.RecognizeResponse.FromString,
                _registered_method=True)
        self.BatchRecognize = channel.unary_unary(
                '/handwriting_inference.HandwritingInference/BatchRecognize',
                request_serializer=handwriting__inference__pb2.BatchRecognizeRequest.SerializeToString,
                response_deserializer=handwriting__inference__pb2.BatchRecognizeResponse.FromString,
                _registered_method=True)
        self.TrainModel = channel.unary_unary(
                '/handwriting_inference.HandwritingInference/TrainModel',
                request_serializer=handwriting__inference__pb2.TrainRequest.SerializeToString,
                response_deserializer=handwriting__inference__pb2.TrainResponse.FromString,
                _registered_method=True)
        self.GetTrainingStatus = channel.unary_unary(
                '/handwriting_inference.HandwritingInference/GetTrainingStatus',
                request_serializer=handwriting__inference__pb2.TrainingStatusRequest.SerializeToString,
                response_deserializer=handwriting__inference__pb2.TrainingStatusResponse.FromString,
                _registered_method=True)
        self.UpdateConfig = channel.unary_unary(
                '/handwriting_inference.HandwritingInference/UpdateConfig',
                request_serializer=handwriting__inference__pb2.ConfigUpdateRequest.SerializeToString,
                response_deserializer=handwriting__inference__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.UpdateUserFeaturesIncremental = channel.unary_unary(
                '/handwriting_inference.HandwritingInference/UpdateUserFeaturesIncremental',
                request_serializer=handwriting__inference__pb2.IncrementalFeatureUpdateRequest.SerializeToString,
                response_deserializer=handwriting__inference__pb2.IncrementalFeatureUpdateResponse.FromString,
                _registered_method=True)
        self.AutoCropSample = channel.unary_unary(
                '/handwriting_inference.HandwritingInference/AutoCropSample',
                request_serializer=handwriting__inference__pb2.AutoCropRequest.SerializeToString,
                response_deserializer=handwriting__inference__pb2.AutoCropResponse.FromString,
                _registered_method=True)


class HandwritingInferenceServicer(object):
    """字迹识别服务
    """

    def Recognize(self, request, context):
        """单张图片识别
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchRecognize(self, request, context):
        """批量识别
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainModel(self, request, context):
        """触发训练
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrainingStatus(self, request, context):
        """获取训练状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConfig(self, request, context):
        """更新配置
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserFeaturesIncremental(self, request, context):
        """增量特征更新
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AutoCropSample(self, request, context):
        """自动裁剪样本
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HandwritingInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=handwriting__inference__pb2.RecognizeRequest.FromString,
                    response_serializer=handwriting__inference__pb2.RecognizeResponse.SerializeToString,
            ),
            'BatchRecognize': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchRecognize,
                    request_deserializer=handwriting__inference__pb2.BatchRecognizeRequest.FromString,
                    response_serializer=handwriting__inference__pb2.BatchRecognizeResponse.SerializeToString,
            ),
            'TrainModel': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainModel,
                    request_deserializer=handwriting__inference__pb2.TrainRequest.FromString,
                    response_serializer=handwriting__inference__pb2.TrainResponse.SerializeToString,
            ),
            'GetTrainingStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingStatus,
                    request_deserializer=handwriting__inference__pb2.TrainingStatusRequest.FromString,
                    response_serializer=handwriting__inference__pb2.TrainingStatusResponse.SerializeToString,
            ),
            'UpdateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfig,
                    request_deserializer=handwriting__inference__pb2.ConfigUpdateRequest.FromString,
                    response_serializer=handwriting__inference__pb2.ConfigResponse.SerializeToString,
            ),
            'UpdateUserFeaturesIncremental': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserFeaturesIncremental,
                    request_deserializer=handwriting__inference__pb2.IncrementalFeatureUpdateRequest.FromString,
                    response_serializer=handwriting__inference__pb2.IncrementalFeatureUpdateResponse.SerializeToString,
            ),
            'AutoCropSample': grpc.unary_unary_rpc_method_handler(
                    servicer.AutoCropSample,
                    request_deserializer=handwriting__inference__pb2.AutoCropRequest.FromString,
                    response_serializer=handwriting__inference__pb2.AutoCropResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'handwriting_inference.HandwritingInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('handwriting_inference.HandwritingInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HandwritingInference(object):
    """字迹识别服务
    """

    @staticmethod
    def Recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/handwriting_inference.HandwritingInference/Recognize',
            handwriting__inference__pb2.RecognizeRequest.SerializeToString,
            handwriting__inference__pb2.RecognizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchRecognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/handwriting_inference.HandwritingInference/BatchRecognize',
            handwriting__inference__pb2.BatchRecognizeRequest.SerializeToString,
            handwriting__inference__pb2.BatchRecognizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/handwriting_inference.HandwritingInference/TrainModel',
            handwriting__inference__pb2.TrainRequest.SerializeToString,
            handwriting__inference__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrainingStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/handwriting_inference.HandwritingInference/GetTrainingStatus',
            handwriting__inference__pb2.TrainingStatusRequest.SerializeToString,
            handwriting__inference__pb2.TrainingStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/handwriting_inference.HandwritingInference/UpdateConfig',
            handwriting__inference__pb2.ConfigUpdateRequest.SerializeToString,
            handwriting__inference__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserFeaturesIncremental(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/handwriting_inference.HandwritingInference/UpdateUserFeaturesIncremental',
            handwriting__inference__pb2.IncrementalFeatureUpdateRequest.SerializeToString,
            handwriting__inference__pb2.IncrementalFeatureUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AutoCropSample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/handwriting_inference.HandwritingInference/AutoCropSample',
            handwriting__inference__pb2.AutoCropRequest.SerializeToString,
            handwriting__inference__pb2.AutoCropResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
