"""Add scheduled tasks tables

Revision ID: 43feee44c541
Revises: 7a1b2c3d4e5f
Create Date: 2026-02-01 14:55:41.644771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43feee44c541'
down_revision = '7a1b2c3d4e5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False, comment='任务名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='任务描述'),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'FAILED', name='schedulestatus'), nullable=False, comment='任务状态'),
    sa.Column('trigger_type', sa.Enum('ONCE', 'INTERVAL', 'CRON', name='scheduletriggertype'), nullable=False, comment='触发器类型'),
    sa.Column('interval_seconds', sa.Integer(), nullable=True, comment='间隔秒数'),
    sa.Column('cron_expression', sa.Text(), nullable=True, comment='Cron表达式'),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=True, comment='执行时间'),
    sa.Column('training_mode', sa.Text(), nullable=False, comment='训练模式: full/incremental'),
    sa.Column('school_id', sa.Integer(), nullable=True, comment='学校ID（可选，为空表示全校）'),
    sa.Column('force_retrain', sa.Boolean(), nullable=True, comment='是否强制重新训练'),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True, comment='最后执行时间'),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True, comment='下次执行时间'),
    sa.Column('total_runs', sa.Integer(), nullable=True, comment='总执行次数'),
    sa.Column('success_runs', sa.Integer(), nullable=True, comment='成功次数'),
    sa.Column('failed_runs', sa.Integer(), nullable=True, comment='失败次数'),
    sa.Column('last_error', sa.Text(), nullable=True, comment='最后一次错误信息'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_tasks_id'), 'scheduled_tasks', ['id'], unique=False)
    op.create_table('scheduled_task_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheduled_task_id', sa.Integer(), nullable=False, comment='定时任务ID'),
    sa.Column('training_job_id', sa.Integer(), nullable=True, comment='关联的训练任务ID'),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('status', sa.Text(), nullable=False, comment='执行状态'),
    sa.Column('output', sa.Text(), nullable=True, comment='执行输出'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.ForeignKeyConstraint(['scheduled_task_id'], ['scheduled_tasks.id'], ),
    sa.ForeignKeyConstraint(['training_job_id'], ['training_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_task_executions_id'), 'scheduled_task_executions', ['id'], unique=False)
    op.alter_column('api_tokens', 'can_read_samples',
               existing_type=mysql.TINYINT(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('api_tokens', 'can_write_samples',
               existing_type=mysql.TINYINT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('api_tokens', 'can_recognize',
               existing_type=mysql.TINYINT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('api_tokens', 'can_read_users',
               existing_type=mysql.TINYINT(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('api_tokens', 'can_manage_users',
               existing_type=mysql.TINYINT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('api_tokens', 'can_manage_schools',
               existing_type=mysql.TINYINT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('api_tokens', 'can_manage_training',
               existing_type=mysql.TINYINT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('api_tokens', 'is_active',
               existing_type=mysql.TINYINT(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('api_tokens', 'is_revoked',
               existing_type=mysql.TINYINT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('api_tokens', 'usage_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    # Note: ix_api_tokens_user_id index is kept as it's needed for foreign key constraint
    op.create_index(op.f('ix_api_tokens_id'), 'api_tokens', ['id'], unique=False)
    op.add_column('training_jobs', sa.Column('scheduled_task_id', sa.Integer(), nullable=True, comment='定时任务ID'))
    op.create_foreign_key(None, 'training_jobs', 'scheduled_tasks', ['scheduled_task_id'], ['id'])
    # Note: user_id index on user_features is kept as it's needed for foreign key constraint
    # op.drop_index(op.f('user_id'), table_name='user_features')
    # op.create_index(op.f('ix_user_features_user_id'), 'user_features', ['user_id'], unique=False)
    # Note: columns that no longer exist in model - not dropping them in this migration
    # op.drop_column('user_features', 'sample_ids')
    # op.drop_column('user_features', 'feature_vector')
    # op.drop_column('user_features', 'updated_at')
    # Note: username index on users table is kept as it's used for uniqueness constraint
    # op.drop_index(op.f('username'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.add_column('user_features', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('user_features', sa.Column('feature_vector', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False))
    op.add_column('user_features', sa.Column('sample_ids', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.drop_index(op.f('ix_user_features_user_id'), table_name='user_features')
    op.create_index(op.f('user_id'), 'user_features', ['user_id'], unique=True)
    op.drop_constraint(None, 'training_jobs', type_='foreignkey')
    op.drop_column('training_jobs', 'scheduled_task_id')
    op.drop_index(op.f('ix_api_tokens_id'), table_name='api_tokens')
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.alter_column('api_tokens', 'usage_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('api_tokens', 'is_revoked',
               existing_type=mysql.TINYINT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('api_tokens', 'is_active',
               existing_type=mysql.TINYINT(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('api_tokens', 'can_manage_training',
               existing_type=mysql.TINYINT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('api_tokens', 'can_manage_schools',
               existing_type=mysql.TINYINT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('api_tokens', 'can_manage_users',
               existing_type=mysql.TINYINT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('api_tokens', 'can_read_users',
               existing_type=mysql.TINYINT(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('api_tokens', 'can_recognize',
               existing_type=mysql.TINYINT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('api_tokens', 'can_write_samples',
               existing_type=mysql.TINYINT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('api_tokens', 'can_read_samples',
               existing_type=mysql.TINYINT(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.drop_index(op.f('ix_scheduled_task_executions_id'), table_name='scheduled_task_executions')
    op.drop_table('scheduled_task_executions')
    op.drop_index(op.f('ix_scheduled_tasks_id'), table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    # ### end Alembic commands ###
