"""Add quota and rate limiting tables

Revision ID: b785cb7ff951
Revises: 43feee44c541
Create Date: 2026-02-01 15:20:57.625648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b785cb7ff951'
down_revision = '43feee44c541'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create quota tables first
    op.create_table('quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quota_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('minute_limit', sa.Integer(), nullable=False),
    sa.Column('hour_limit', sa.Integer(), nullable=False),
    sa.Column('day_limit', sa.Integer(), nullable=False),
    sa.Column('month_limit', sa.Integer(), nullable=False),
    sa.Column('total_limit', sa.Integer(), nullable=False),
    sa.Column('minute_used', sa.Integer(), nullable=False),
    sa.Column('hour_used', sa.Integer(), nullable=False),
    sa.Column('day_used', sa.Integer(), nullable=False),
    sa.Column('month_used', sa.Integer(), nullable=False),
    sa.Column('total_used', sa.Integer(), nullable=False),
    sa.Column('minute_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hour_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('day_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('month_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quota_type_school_id', 'quotas', ['quota_type', 'school_id'], unique=False)
    op.create_index('ix_quota_type_user_id', 'quotas', ['quota_type', 'user_id'], unique=False)
    op.create_index(op.f('ix_quotas_id'), 'quotas', ['id'], unique=False)
    op.create_index(op.f('ix_quotas_quota_type'), 'quotas', ['quota_type'], unique=False)
    op.create_index(op.f('ix_quotas_school_id'), 'quotas', ['school_id'], unique=False)
    op.create_index(op.f('ix_quotas_user_id'), 'quotas', ['user_id'], unique=False)
    op.create_table('quota_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('quota_type', sa.String(length=20), nullable=False),
    sa.Column('quota_id', sa.Integer(), nullable=True),
    sa.Column('recognition_log_id', sa.Integer(), nullable=True),
    sa.Column('is_allowed', sa.Integer(), nullable=False),
    sa.Column('deny_reason', sa.String(length=100), nullable=True),
    sa.Column('usage_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recognition_log_id'], ['recognition_logs.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quota_usage_logs_id'), 'quota_usage_logs', ['id'], unique=False)
    op.create_index(op.f('ix_quota_usage_logs_school_id'), 'quota_usage_logs', ['school_id'], unique=False)
    op.create_index(op.f('ix_quota_usage_logs_user_id'), 'quota_usage_logs', ['user_id'], unique=False)
    op.create_index('ix_quota_usage_school_created', 'quota_usage_logs', ['school_id', 'created_at'], unique=False)
    op.create_index('ix_quota_usage_user_created', 'quota_usage_logs', ['user_id', 'created_at'], unique=False)

    # Don't drop indexes that are needed for foreign key constraints
    # Update user_features index if needed
    try:
        op.create_index(op.f('ix_user_features_user_id'), 'user_features', ['user_id'], unique=False)
    except Exception:
        pass  # Index might already exist

    # Don't drop the username index from users table as it's needed for uniqueness
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop quota tables first
    op.drop_index('ix_quota_usage_user_created', table_name='quota_usage_logs')
    op.drop_index('ix_quota_usage_school_created', table_name='quota_usage_logs')
    op.drop_index(op.f('ix_quota_usage_logs_user_id'), table_name='quota_usage_logs')
    op.drop_index(op.f('ix_quota_usage_logs_school_id'), table_name='quota_usage_logs')
    op.drop_index(op.f('ix_quota_usage_logs_id'), table_name='quota_usage_logs')
    op.drop_table('quota_usage_logs')
    op.drop_index(op.f('ix_quotas_user_id'), table_name='quotas')
    op.drop_index(op.f('ix_quotas_school_id'), table_name='quotas')
    op.drop_index(op.f('ix_quotas_quota_type'), table_name='quotas')
    op.drop_index(op.f('ix_quotas_id'), table_name='quotas')
    op.drop_index('ix_quota_type_user_id', table_name='quotas')
    op.drop_index('ix_quota_type_school_id', table_name='quotas')
    op.drop_table('quotas')
    # ### end Alembic commands ###
